name: Bundle a μpkg package and create a GitHub release with it
description: Uses upkg-bundle to create a μpkg tarball package
inputs:
  upkg-version:
    description: The version of μpkg to use for bundling
    default: latest
    required: false
  name:
    description: The name of the package, will override the name already set in `upkg.json`
    default: ""
    required: false
  version:
    description: The version to write to upkg.json, corresponds to `-V` in `upkg bundle`
    default: "---auto---"
    required: false
  paths:
    description: Argument (space separated) list of relative paths to files and directories to include in the package.
    default: ""
    required: false
  working-directory:
    description: The working directory to change to before determining the version and bundling. This disables automatic checkout.
    default: ""
    required: false
  release-name:
    description: Name of the github release.
    default: "---auto---"
    required: false
  release-message:
    description: The github release message to add after the installation instructions.
    default: "---auto---"
    required: false
outputs:
  name:
    description: The name of the released package
    value: ${{ steps.bundle.outputs.name }}
  version:
    description: The version of the released package
    value: ${{ steps.bundle.outputs.version }}
  download-url:
    description: The download URL of the released package
    value: https://github.com/${{ github.repository }}/releases/download/${{ steps.release.outputs.tag }}/${{ steps.basename.outputs.basename }}
  sha256:
    description: The SHA-256 checksum of the released package
    value: ${{ steps.bundle.outputs.sha256 }}
  release-name:
    description: Name of the github release.
    value: ${{ inputs.release-name == '---auto---' && (inputs.version == '---auto---' && steps.bundle.outputs.version || inputs.version) || inputs.release-name }}
  release-message:
    description: The github release message that has been appended to the installation instructions.
    value: ${{ inputs.release-message == '---auto---' && steps.release.outputs.message || inputs.release-message }}
runs:
  using: composite
  steps:
  - uses: actions/checkout@v4
    with:
      ref: ${{ github.ref }}
    if: ${{ inputs.working-directory == '' }}
  - uses: orbit-online/upkg-bundle@v1
    id: bundle
    with:
      upkg-version: ${{ inputs.upkg-version }}
      name: ${{ inputs.name }}
      version: ${{ inputs.version }}
      paths: ${{ inputs.paths }}
      working-directory: ${{ inputs.working-directory || '.' }}
  - name: Determine bundle location
    id: bundle_dest
    shell: bash
    run: printf "dest=%s\n" "$(realpath "${{ steps.bundle.outputs.dest }}")" >> $GITHUB_OUTPUT
    working-directory: ${{ inputs.working-directory || '.' }}
  - uses: orbit-online/git-release@v1
    if: "${{ inputs.release-message == '---auto---' }}"
    id: release
    with:
      working-directory: ${{ inputs.working-directory || '.' }}
  - uses: ncipollo/release-action@v1
    with:
      name: ${{ inputs.release-name == '---auto---' && (inputs.version == '---auto---' && steps.bundle.outputs.version || inputs.version) || inputs.release-name }}
      body: |
        Install/depend on this package using [μpkg](https://github.com/orbit-online/upkg):
        ```
        upkg add 'https://github.com/${{ github.repository }}/releases/download/${{ inputs.release-name == '---auto---' && (inputs.version == '---auto---' && steps.bundle.outputs.version || inputs.version) || inputs.release-name }}/${{ steps.bundle.outputs.basename }}' ${{ steps.bundle.outputs.sha256 }}
        ```

        ${{ inputs.release-message == '---auto---' && steps.release.outputs.message || inputs.release-message }}
      draft: false
      prerelease: false
      artifacts: ${{ steps.bundle_dest.outputs.dest }}
      artifactErrorsFailBuild: true
      artifactContentType: application/gzip
